// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as EXTROSPECT_ADDR,
    BYTECODE_HASH as EXTROSPECT_HASH
} from "../generated/candidate/Extrospect.sol";

/// @title LibExtrospectDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `Extrospect`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibExtrospectDeploy {
    address constant EXTROSPECT_DEPLOYED_ADDRESS = EXTROSPECT_ADDR;
    bytes32 constant EXTROSPECT_DEPLOYED_CODEHASH = EXTROSPECT_HASH;
}
