// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

import {DeployCandidate, DeploySuite, RainDeploySuitesBase} from "./RainDeploySuitesBase.sol";
import {Extrospect} from "../concrete/Extrospect.sol";
import {
    CREATION_CODE as EXTROSPECT_CREATION_CODE_CANDIDATE,
    RUNTIME_CODE as EXTROSPECT_RUNTIME_CODE_CANDIDATE
} from "../generated/candidate/Extrospect.sol";
import {LibExtrospectDeploy} from "../lib/LibExtrospectDeploy.sol";
import {LibReleasedSuites} from "../lib/LibReleasedSuites.sol";

/// @title ExtrospectDeploySuites
/// @notice Everything this repo deploys, declared ONCE.
///
/// These contracts inherit it, and nothing else declares a suite:
///
/// - `script/Deploy.sol` broadcasts from it
/// - `script/Build.sol` generates the snapshot, the alias lib and the
///   released-suites libs from it — the named candidate below is the template
///   it emits from, which is why it inherits the declaration rather than
///   restating the key, the artifact path and the dependency list
/// - `ExtrospectDeploySnapshotTest` checks its record against its creation
///   code
/// - `ExtrospectDeployChainTest` checks it against every chain
///
/// So "the deploy script broadcasts one contract while the tests verify
/// another" is not a thing that can be true here. Not because something checks
/// for it — because there is only one list, and they all read it.
///
/// It lives in `src/` rather than `test/` because `.soldeerignore` excludes
/// `test/` from the published package, and in a deploy repo the deployment
/// process is the product.
///
/// Half of it is written by hand and half is generated: the candidate below is
/// the declaration, and the whole released side — the per-contract lib and the
/// aggregate that concatenates it — comes from `script/Build.sol`, which emits
/// it from the frozen record. Nothing about a release is written here.
abstract contract ExtrospectDeploySuites is RainDeploySuitesBase {
    /// @inheritdoc RainDeploySuitesBase
    /// @dev Generated by `script/Build.sol` from the frozen
    /// `src/generated/<tag>/` record, in the same call that writes it. The
    /// record and the declaration of it therefore cannot disagree — which
    /// matters because a release missing from the declaration is a release
    /// every check quietly stops asking about, while the whole suite stays
    /// green.
    ///
    /// Empty until the first release is cut. The rolling `candidate/` snapshot
    /// is not a release and does exist.
    function releasedSuites() internal pure override returns (DeploySuite[] memory) {
        return LibReleasedSuites.releasedSuites();
    }

    /// @inheritdoc RainDeploySuitesBase
    /// @dev One entry per contract this repo deploys, which is one. A second
    /// deployed contract is a second named candidate below, a second entry
    /// here, and a second entry in `script/Build.sol`'s generated-contract
    /// list — nothing else. The released declaration follows from that entry
    /// rather than being another place to edit: `script/Build.sol` generates
    /// the per-contract released lib AND the aggregate `releasedSuites()`
    /// reads from that one list.
    function candidateSuites() internal pure override returns (DeployCandidate[] memory) {
        DeployCandidate[] memory candidates = new DeployCandidate[](1);
        candidates[0] = extrospectCandidate();
        return candidates;
    }

    /// This repo's rolling `Extrospect` candidate.
    ///
    /// The pins in `LibExtrospectDeploy` are aliased from the generated
    /// snapshot, and they are what the internal group checks the derivation
    /// against and what the broadcast asserts against before it forks
    /// anything.
    ///
    /// The creation code and runtime code are RECORDED, read from the rolling
    /// `src/generated/candidate/` snapshot. That is what makes the source
    /// anchor mean something: it compares the recorded creation code against
    /// `type(Extrospect).creationCode`, so editing the contract without
    /// re-running `script/Build.sol` fails.
    ///
    /// `Extrospect` reads nothing and calls nothing at construction, so it has
    /// no dependency that must already be on chain.
    ///
    /// Named rather than reached by index into `candidateSuites`, because
    /// `script/Build.sol` needs THIS candidate specifically — a released-suites
    /// lib describes one contract — and a positional read silently describes a
    /// different contract the moment the list is reordered. Naming it here
    /// also keeps the suite key, the artifact path and the dependency list
    /// spelled once: `Build.sol` inherits this rather than restating them.
    /// @return The candidate.
    function extrospectCandidate() internal pure returns (DeployCandidate memory) {
        return DeployCandidate({
            snapshot: DeploySuite({
                suite: "extrospect",
                creationCode: EXTROSPECT_CREATION_CODE_CANDIDATE,
                storedDeployedAddress: LibExtrospectDeploy.EXTROSPECT_DEPLOYED_ADDRESS,
                storedBytecodeHash: LibExtrospectDeploy.EXTROSPECT_DEPLOYED_CODEHASH,
                storedRuntimeCode: EXTROSPECT_RUNTIME_CODE_CANDIDATE,
                artifactPath: "src/concrete/Extrospect.sol:Extrospect",
                dependencies: new address[](0)
            }),
            sourceCreationCode: type(Extrospect).creationCode
        });
    }
}
